### PR TITLE
feat(4.22.0): bumped to aws provider 4.22.0 and added grafana, amp

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: haarchri <chhaar30@googlemail.com>

### Description of your changes
- bumped from 3.52.0 to 4.22.0 terraform aws-provider
- added grafana
- added amp
- changed route53 include list, trafficpolicy* was added - have no use-case to test - so skipped for now 2 resources

**breaking changed because of provider bump:**

- [elasticache.aws.jet.crossplane.io_replicationgroups.yaml](https://github.com/crossplane-contrib/provider-jet-aws/pull/214/files#diff-d8194eaf70eb1041b52094d19c4c18a7c81175773578678922e444e88f7c001c)
autoMinorVersionUpgrade changed type: boolean to type: string

- [elbv2.aws.jet.crossplane.io_lbtargetgroups.yaml](https://github.com/crossplane-contrib/provider-jet-aws/pull/214/files#diff-1748895a71f990f42591d6eab3c0536a126036423c6c982ee1302dfecf1d7b9a)
deregistrationDelay: changed type: number to type: string

- [s3.aws.jet.crossplane.io_buckets.yaml](https://github.com/crossplane-contrib/provider-jet-aws/pull/214/files#diff-8c15c02dd11eb04879d88de7b9ce3fc208b02abb32618311bbba4b53e6e26750)
Changed field websiteDomain and websiteEndpoint to additionalProperties

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

Grafana and AMP (Prometheus) 
```
NAME                                                       READY   SYNCED   EXTERNAL-NAME   AGE
workspace.grafana.aws.jet.crossplane.io/sample-workspace   True    True     g-aa57ea1300    52m

NAME                                                             READY   SYNCED   EXTERNAL-NAME        AGE
roleassociation.grafana.aws.jet.crossplane.io/sample-workspace   True    True     g-aa57ea1300/ADMIN   29m

NAME                                                   READY   SYNCED   EXTERNAL-NAME                             AGE
workspace.amp.aws.jet.crossplane.io/sample-workspace   True    True     ws-a9f6db36-8752-419a-ba71-5021769790f7   14m
```

### CODE REVIEW

**Comment by haarchri** [comment]
@muvaf  @jbw976  regarding api group version for new resources like grafana, amp/prometheus ? did we use v1alpha1 or v1alpha2 ?

**Comment by haarchri** [comment]
currently checking why observed is failed for existing resources with:

```.657479674736587e+09   DEBUG   events  Warning {"object": {"kind":"LBTargetGroup","name":"sample-lambda-targetgroup","uid":"34dee55d-e325-4b74-ae36-62ba5a45d01f","apiVersion":"elbv2.aws.jet.crossplane.io/v1alpha2","resourceVersion":"282025"}, "reason": "CannotObserveExternalResource", "message": "cannot run refresh: refresh failed: Provider requirements cannot be satisfied by locked dependencies: The following required providers are not installed:\n\n- registry.terraform.io/hashicorp/aws (4.22.0)\n\nPlease run \"terraform init\"."}```

**Comment by jbw976** [comment]
@haarchri I believe new resources, that are configured with external name, late init, cross resource references, etc. have been introduced at v1alpha2 in the past :)

**Comment by ytsarev** [comment]
@haarchri maybe it is a local invocation artifact. What will happen if you clean up the temporary terraform workspace directory?

**Comment by haarchri** [comment]
It's the same -  i cleaned up because otherwise the make generate is not working with new version

**Comment by ytsarev** [comment]
We may be talking about different directories, I mean something like `/var/folders/sx/$uuid/T/$another_uuid/` on macos or similar temp dir on linux.

They contain
```
main.tf.json
terraform.tfstate
terraform.tfstate.backup
``` 

of specific MR and definitely should not affect any code generation

**Comment by haarchri** [comment]
@ytsarev  yeah - thanks for the hint

` /var/folders/cz/2y38s5w127n7vc997qmxcsnr0000gn/T/a986a902-20ff-433a-b8cb-6b12c97a9208`
removed the folder now it looks better

**Review by muvaf — APPROVED** [review]

**Pull request merged**
